### ISSUE TITLE
Link issues to slack

### ISSUE THREAD

**Issue by ivillasante** [bbglab/bbgwiki#168]

**Comment by ScarpettaDavide** [comment]
Done using [Zapier](https://zapier.com/app/home), from now on a new issue will trigger a message with the corresponding link on the bbgwiki slack channel.
With the free version we have 100 message/month, i think it should be enough for our purpose.

**Comment by msguixe** [comment]
This issue was reopened (probably a mistake)
Zapier is working perfectly :+1:
