### ISSUE TITLE
BBGwiki | add link to Discurso

### ISSUE THREAD

**Issue by koszulordie** [bbglab/bbgwiki#170]
Add a simple page with a download link to the document Nuria L wrote when she was appointed member of the *Real Academia de Ciencias Exactas, Físicas y Naturales*, also known as the *Discurso*. This is a good lay introduction to somatic evolution and the work that has been conducted by people in the lab during the last decade --  at the moment it is only available in Spanish. Particularly interesting for Spanish-proficient new members of the lab.

**Comment by FerriolCalvet** [comment]
https://rac.es/ficheros/doc/fd78e7d5bbaabf70.pdf

**Comment by FerriolCalvet** [comment]
not needed becaue it is already in the lab website
