### ISSUE TITLE
Learning tools | Create a learning page

### ISSUE THREAD

**Issue by migrau** [bbglab/bbgwiki#176]
## Description

Create a _Learning_ section with all the content included in the old dashboard https://bbgcloud.irbbarcelona.org/apps/external/1/
It could be extended/updated with public online resouces of interest.

**Comment by AxelRosendahlHuber** [comment]
I am working on this issue. 

List of parts in the _Learning_ section which need to be added (or are already in some other form in the github repository): 
In a way, much of the learning section parts (which was a mixed bag of resources) is now distributed alongside multiple parts of the bbgwiki. Many of the presentations and tutorials (especially the home-made google slides presentations) are of high quality and very useful

- Get started with Python, Python classes,Python decorators,Good practices, Write documentation:
 -> moved to Tools/Programming/Python/Python_resources
- Git (already present at: "https://bbglab.github.io/bbgwiki/Tools/Programming/git/") - no changes
- Write docs: (was python-specific), placed in Tools/Programming/Python/Python_resources
- Singularity: Added presentation link to the "Further reading" part of the BBGwiki Tools/Singularity/Overview
- Linux & Containers: Added presentation link to the "Further reading" part of the BBGwiki Tools/Singularity/Overview
- Points of view: Moved to "Plots and scripts" -> Advice-Tips_data_visualization
- BBGgallery of plots: Moved to "Plots and scripts" -> Advice-Tips_data_visualization
-
